#!/usr/bin/env bash
# WSL2 settings — %UserProfile%\.wslconfig on the Windows side and
# /etc/wsl.conf in the distro. Pure config, and only on WSL: every other host
# skips it.

if ! { [ -n "${WSL_DISTRO_NAME:-}" ] || grep -qsi microsoft /proc/version; }; then
  ok "skipped .wslconfig (not running under WSL)"
  return 0
fi

# Copied, not linked: Windows reads .wslconfig before the VM (and its \\wsl$
# share) exists, so a symlink into this repo would never resolve. Repo edits
# go live on the next --config-only run.
winhome="$(wslpath "$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r')")"
[ -d "$winhome" ] || { warn "could not resolve %UserProfile% — .wslconfig not installed"; return 0; }
dest="$winhome/.wslconfig"
src="$(config_dir wsl)/wslconfig"

if [ -f "$dest" ] && cmp -s "$src" "$dest"; then
  ok ".wslconfig up to date ($dest)"
else
  if [ -e "$dest" ]; then
    cp "$dest" "$dest.bak.$$"; warn "backed up $dest -> $dest.bak.$$"
  fi
  cp "$src" "$dest"
  ok "installed .wslconfig -> $dest"
  warn "run 'wsl --shutdown' from Windows to apply (restarts every distro)"
fi

# /etc/wsl.conf — root-owned, so copied with $SUDO rather than linked.
src="$(config_dir wsl)/wsl.conf"
if [ -f /etc/wsl.conf ] && cmp -s "$src" /etc/wsl.conf; then
  ok "/etc/wsl.conf up to date"
else
  [ -e /etc/wsl.conf ] && $SUDO cp /etc/wsl.conf "/etc/wsl.conf.bak.$$" \
    && warn "backed up /etc/wsl.conf -> /etc/wsl.conf.bak.$$"
  $SUDO cp "$src" /etc/wsl.conf
  ok "installed /etc/wsl.conf"
  warn "run 'wsl --shutdown' from Windows to apply (restarts every distro)"
fi

# Old VPN workaround: a hand-written resolv.conf, often chattr +i so WSL can't
# replace it. While it is a regular file WSL leaves it alone even with
# generateResolvConf on — remove it so the next boot links WSL's own.
if ! grep -qsiE '^\s*generateResolvConf\s*=\s*false' /etc/wsl.conf \
   && [ -f /etc/resolv.conf ] && [ ! -L /etc/resolv.conf ] \
   && ! grep -qs 'generated by WSL' /etc/resolv.conf; then
  $SUDO cp /etc/resolv.conf "/etc/resolv.conf.bak.$$"
  $SUDO chattr -i /etc/resolv.conf 2>/dev/null || true
  $SUDO rm -f /etc/resolv.conf
  warn "removed static /etc/resolv.conf (backup: /etc/resolv.conf.bak.$$) — DNS is down until 'wsl --shutdown'"
fi
